# Generated by Django 3.1.1 on 2020-11-09 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('constituency', models.IntegerField(default=100, primary_key=True, serialize=False)),
                ('constituency_name', models.CharField(max_length=20)),
                ('constituency_description', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=100)),
                ('posted_by_name', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('sector_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sector_name', models.CharField(max_length=20)),
                ('sector_scope', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20)),
                ('uemail', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('upassword', models.CharField(max_length=20)),
                ('umobile', models.CharField(blank=True, max_length=10, null=True)),
                ('uconsname', models.CharField(default='basavangudi', max_length=20)),
                ('usertype', models.CharField(max_length=10, null=True)),
                ('const', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdb.constituency')),
            ],
        ),
        migrations.CreateModel(
            name='News_Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_title', models.CharField(max_length=50)),
                ('feed_description', models.CharField(max_length=400)),
                ('feed_date', models.DateTimeField(auto_now=True, null=True)),
                ('constituency_name', models.CharField(max_length=20)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdb.constituency')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_subject', models.CharField(max_length=50)),
                ('complaint_details', models.CharField(max_length=300)),
                ('posted_by_name', models.CharField(max_length=50)),
                ('no_up_vote', models.IntegerField(null=True)),
                ('sector_name', models.CharField(max_length=30)),
                ('const_name', models.CharField(max_length=50)),
                ('upvoted_by', models.CharField(max_length=50, null=True)),
                ('const', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdb.constituency')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdb.sector')),
            ],
        ),
    ]
