# Generated by Django 3.1.1 on 2020-12-04 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appdb', '0002_auto_20201204_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='qcons',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='appdb.constituency'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='qcons_name',
            field=models.CharField(default='Basavangudi', max_length=50),
        ),
    ]
