# Generated by Django 3.1.1 on 2020-11-09 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appdb', '0002_auto_20201109_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='qconst',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appdb.constituency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='query',
            name='qconst_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
