# Generated by Django 3.1.1 on 2020-11-09 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appdb', '0003_auto_20201109_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('answered_by_name', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('ansq_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdb.query')),
            ],
        ),
    ]
