# Generated by Django 3.1.1 on 2020-11-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdb', '0004_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='answered_by',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
