# Generated by Django 3.1.1 on 2021-01-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdb', '0004_assembly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembly',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
    ]
