# Generated by Django 3.1.1 on 2021-01-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdb', '0005_auto_20210103_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_feed',
            name='newsimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
