# Generated by Django 3.1.1 on 2020-11-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdb', '0005_query_answered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='answered_by',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
