# Generated by Django 3.1.1 on 2021-01-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdb', '0006_news_feed_newsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_feed',
            name='newsimage',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
