# Generated by Django 3.1.1 on 2020-11-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdb', '0006_auto_20201109_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='ansq_id',
            new_name='query',
        ),
    ]
