# Generated by Django 3.1.1 on 2021-01-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdb', '0007_auto_20210107_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_feed',
            name='newsimage',
            field=models.ImageField(default=0, upload_to='img'),
        ),
    ]
