# Generated by Django 3.1.1 on 2020-11-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdb', '0007_auto_20201109_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
