# Generated by Django 3.1.1 on 2021-01-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdb', '0008_auto_20210107_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_feed',
            name='newsimage',
            field=models.ImageField(upload_to='img'),
        ),
    ]
