# Generated by Django 3.1.1 on 2021-01-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdb', '0009_auto_20210107_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_feed',
            name='newsimage',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
