# Generated by Django 3.1.1 on 2020-11-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdb', '0009_auto_20201109_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
