# Generated by Django 3.1.1 on 2021-01-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdb', '0010_auto_20210107_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_feed',
            name='newsimage',
            field=models.ImageField(upload_to=''),
        ),
    ]
