# Generated by Django 3.1.1 on 2021-01-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdb', '0012_auto_20210107_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_feed',
            name='newsimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
