# Generated by Django 3.1.1 on 2021-01-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdb', '0014_auto_20210107_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaintimage',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
