# Generated by Django 3.1.1 on 2020-11-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdb', '0014_auto_20201109_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uconsname',
            field=models.CharField(default='Basavangudi', max_length=20),
        ),
    ]
